// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.3
// source: proto_files/bank_and_accounts.proto

package proto_files

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WalletID string `protobuf:"bytes,2,opt,name=walletID,proto3" json:"walletID,omitempty"`
	Balance  uint64 `protobuf:"varint,3,opt,name=balance,proto3" json:"balance,omitempty"`
}

func (x *Account) Reset() {
	*x = Account{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_bank_and_accounts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_bank_and_accounts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proto_files_bank_and_accounts_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetWalletID() string {
	if x != nil {
		return x.WalletID
	}
	return ""
}

func (x *Account) GetBalance() uint64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type CreateAccountParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateAccountParams) Reset() {
	*x = CreateAccountParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_bank_and_accounts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAccountParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountParams) ProtoMessage() {}

func (x *CreateAccountParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_bank_and_accounts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountParams.ProtoReflect.Descriptor instead.
func (*CreateAccountParams) Descriptor() ([]byte, []int) {
	return file_proto_files_bank_and_accounts_proto_rawDescGZIP(), []int{1}
}

type GetAccountsParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAccountsParams) Reset() {
	*x = GetAccountsParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_bank_and_accounts_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountsParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountsParams) ProtoMessage() {}

func (x *GetAccountsParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_bank_and_accounts_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountsParams.ProtoReflect.Descriptor instead.
func (*GetAccountsParams) Descriptor() ([]byte, []int) {
	return file_proto_files_bank_and_accounts_proto_rawDescGZIP(), []int{2}
}

type GenerateAddressParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GenerateAddressParams) Reset() {
	*x = GenerateAddressParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_bank_and_accounts_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenerateAddressParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateAddressParams) ProtoMessage() {}

func (x *GenerateAddressParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_bank_and_accounts_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateAddressParams.ProtoReflect.Descriptor instead.
func (*GenerateAddressParams) Descriptor() ([]byte, []int) {
	return file_proto_files_bank_and_accounts_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateAddressParams) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DepositParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *DepositParams) Reset() {
	*x = DepositParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_bank_and_accounts_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositParams) ProtoMessage() {}

func (x *DepositParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_bank_and_accounts_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositParams.ProtoReflect.Descriptor instead.
func (*DepositParams) Descriptor() ([]byte, []int) {
	return file_proto_files_bank_and_accounts_proto_rawDescGZIP(), []int{4}
}

func (x *DepositParams) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DepositParams) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type WithdrawalParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount uint64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *WithdrawalParams) Reset() {
	*x = WithdrawalParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_files_bank_and_accounts_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawalParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawalParams) ProtoMessage() {}

func (x *WithdrawalParams) ProtoReflect() protoreflect.Message {
	mi := &file_proto_files_bank_and_accounts_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawalParams.ProtoReflect.Descriptor instead.
func (*WithdrawalParams) Descriptor() ([]byte, []int) {
	return file_proto_files_bank_and_accounts_proto_rawDescGZIP(), []int{5}
}

func (x *WithdrawalParams) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WithdrawalParams) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_proto_files_bank_and_accounts_proto protoreflect.FileDescriptor

var file_proto_files_bank_and_accounts_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x62, 0x61,
	0x6e, 0x6b, 0x5f, 0x61, 0x6e, 0x64, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x70, 0x61, 0x79, 0x22,
	0x4f, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x77, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x22, 0x15, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x27, 0x0a, 0x15,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x37, 0x0a, 0x0d, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x3a,
	0x0a, 0x10, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x32, 0xcf, 0x02, 0x0a, 0x0e, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x41, 0x0a,
	0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1d,
	0x2e, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x70, 0x61, 0x79, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x11, 0x2e,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x70, 0x61, 0x79, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x3f, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12,
	0x1b, 0x2e, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x70, 0x61, 0x79, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x11, 0x2e, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x70, 0x61, 0x79, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x30,
	0x01, 0x12, 0x45, 0x0a, 0x0f, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x2e, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x70, 0x61, 0x79, 0x2e,
	0x47, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x11, 0x2e, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x70, 0x61, 0x79,
	0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x35, 0x0a, 0x07, 0x44, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x12, 0x17, 0x2e, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x70, 0x61, 0x79, 0x2e, 0x44,
	0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x11, 0x2e, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x70, 0x61, 0x79, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x3b, 0x0a, 0x0a, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x61, 0x6c, 0x12, 0x1a, 0x2e,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x70, 0x61, 0x79, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61,
	0x77, 0x61, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x11, 0x2e, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x70, 0x61, 0x79, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x42, 0x0e, 0x5a, 0x0c,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_files_bank_and_accounts_proto_rawDescOnce sync.Once
	file_proto_files_bank_and_accounts_proto_rawDescData = file_proto_files_bank_and_accounts_proto_rawDesc
)

func file_proto_files_bank_and_accounts_proto_rawDescGZIP() []byte {
	file_proto_files_bank_and_accounts_proto_rawDescOnce.Do(func() {
		file_proto_files_bank_and_accounts_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_files_bank_and_accounts_proto_rawDescData)
	})
	return file_proto_files_bank_and_accounts_proto_rawDescData
}

var file_proto_files_bank_and_accounts_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_files_bank_and_accounts_proto_goTypes = []interface{}{
	(*Account)(nil),               // 0: bank_and_accounts.Account
	(*CreateAccountParams)(nil),   // 1: bank_and_accounts.CreateAccountParams
	(*GetAccountsParams)(nil),     // 2: bank_and_accounts.GetAccountsParams
	(*GenerateAddressParams)(nil), // 3: bank_and_accounts.GenerateAddressParams
	(*DepositParams)(nil),         // 4: bank_and_accounts.DepositParams
	(*WithdrawalParams)(nil),      // 5: bank_and_accounts.WithdrawalParams
}
var file_proto_files_bank_and_accounts_proto_depIdxs = []int32{
	1, // 0: bank_and_accounts.AccountService.CreateAccount:input_type -> bank_and_accounts.CreateAccountParams
	2, // 1: bank_and_accounts.AccountService.GetAccounts:input_type -> bank_and_accounts.GetAccountsParams
	3, // 2: bank_and_accounts.AccountService.GenerateAddress:input_type -> bank_and_accounts.GenerateAddressParams
	4, // 3: bank_and_accounts.AccountService.Deposit:input_type -> bank_and_accounts.DepositParams
	5, // 4: bank_and_accounts.AccountService.Withdrawal:input_type -> bank_and_accounts.WithdrawalParams
	0, // 5: bank_and_accounts.AccountService.CreateAccount:output_type -> bank_and_accounts.Account
	0, // 6: bank_and_accounts.AccountService.GetAccounts:output_type -> bank_and_accounts.Account
	0, // 7: bank_and_accounts.AccountService.GenerateAddress:output_type -> bank_and_accounts.Account
	0, // 8: bank_and_accounts.AccountService.Deposit:output_type -> bank_and_accounts.Account
	0, // 9: bank_and_accounts.AccountService.Withdrawal:output_type -> bank_and_accounts.Account
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_files_bank_and_accounts_proto_init() }
func file_proto_files_bank_and_accounts_proto_init() {
	if File_proto_files_bank_and_accounts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_files_bank_and_accounts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Account); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_bank_and_accounts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAccountParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_bank_and_accounts_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountsParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_bank_and_accounts_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenerateAddressParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_bank_and_accounts_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_files_bank_and_accounts_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawalParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_files_bank_and_accounts_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_files_bank_and_accounts_proto_goTypes,
		DependencyIndexes: file_proto_files_bank_and_accounts_proto_depIdxs,
		MessageInfos:      file_proto_files_bank_and_accounts_proto_msgTypes,
	}.Build()
	File_proto_files_bank_and_accounts_proto = out.File
	file_proto_files_bank_and_accounts_proto_rawDesc = nil
	file_proto_files_bank_and_accounts_proto_goTypes = nil
	file_proto_files_bank_and_accounts_proto_depIdxs = nil
}
